name: ui_components
description: "Design system for AQUA flutter projects"
version: 0.0.1+1

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.7
  moment_dart: ^4.0.1
  intl: any
  fl_chart: ^0.66.2
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: 5.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/fonts/roboto_mono/
    - assets/svgs/
    - assets/svgs/currency/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBold.ttf
          weight: 600
    - family: FiraMono
      fonts:
        - asset: assets/fonts/fira_mono/FiraMono-Medium.ttf
          weight: 500

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
  assets:
    enabled: true
    outputs:
      class_name: AquaUiAssets
      package_parameter_enabled: true
  fonts:
    enabled: true
    outputs:
      class_name: AquaFontFamily
