import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:ui_components/ui_components.dart';
import 'package:ui_components_playground/shared/extensions/extensions.dart';

import '../providers/providers.dart';

class ListItemDemoPage extends HookConsumerWidget {
  const ListItemDemoPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = ref.watch(prefsProvider).selectedTheme;
    final iconLeading = useMemoized(() {
      return AquaIcon.scan(
        color: theme.colors.textPrimary,
      );
    }, [theme]);
    final iconTrailing = useMemoized(() {
      return AquaIcon.chevronRight(
        color: theme.colors.textPrimary,
        size: 18,
      );
    }, [theme]);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      scrollDirection: Axis.horizontal,
      physics: const BouncingScrollPhysics(),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 343),
            child: Column(
              children: [
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  selected: true,
                  colors: theme.colors,
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  selected: true,
                  colors: theme.colors,
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitleTrailing: 'Secondary Right',
                  selected: true,
                  colors: theme.colors,
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  selected: true,
                  colors: theme.colors,
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  subtitleTrailing: 'Secondary Right',
                  selected: true,
                  colors: theme.colors,
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  selected: true,
                  colors: theme.colors,
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  selected: true,
                  colors: theme.colors,
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  selected: true,
                  colors: theme.colors,
                  iconLeading: iconLeading,
                  iconTrailing: iconTrailing,
                ),
              ],
            ),
          ),
          const SizedBox(width: 20),
          ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 343),
            child: Column(
              children: [
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                ),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  iconLeading: iconLeading,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconLeading: iconLeading,
                ),
              ],
            ),
          ),
          const SizedBox(width: 20),
          ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 343),
            child: Column(
              children: [
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconTrailing: iconTrailing,
                ),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  subtitleTrailing: 'Secondary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  iconTrailing: iconTrailing,
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                  iconTrailing: iconTrailing,
                ),
              ],
            ),
          ),
          const SizedBox(width: 20),
          ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 343),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitleTrailing: 'Secondary Right',
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  subtitleTrailing: 'Secondary Right',
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                ),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitleTrailing: 'Secondary Right',
                ),
                const SizedBox(height: 25),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  subtitleTrailing: 'Secondary Right',
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                ),
                const SizedBox(height: 20),
                AquaListItem(
                  onTap: () {},
                  selected: true,
                  colors: theme.colors,
                  title: 'Primary Left',
                  subtitle: 'Secondary Left',
                  titleTrailing: 'Primary Right',
                  subtitleTrailing: 'Secondary Right',
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
